package orchestrator

import (
	"context"
	"fmt"
	"strings"

	"github.com/giovannialves/corvex/internal/provider"
	"github.com/giovannialves/corvex/internal/types"
)

// ReviewVerdict represents the outcome of a task review.
type ReviewVerdict string

const (
	VerdictPass ReviewVerdict = "PASS"
	VerdictFail ReviewVerdict = "FAIL"
)

// ReviewResult carries the reviewer's verdict and analysis summary.
type ReviewResult struct {
	Verdict ReviewVerdict
	// Category, when non-empty, classifies a failed verdict (e.g.
	// "wrong-approach", "missing-edge-case", "flaky-test"). Used by the
	// escalation engine. Empty for PASS verdicts or when the Reviewer
	// did not emit a CATEGORY: line.
	Category   string
	Summary    string
	CostUSD    float64
	TokensIn   int
	TokensOut  int
	DurationMs int64
}

// Reviewer independently verifies that a task was completed correctly.
type Reviewer struct {
	progressBase
	provider provider.Provider
	model    string
	workDir  string
}

// NewReviewer creates a Reviewer bound to the given provider and model.
func NewReviewer(p provider.Provider, model, workDir string) *Reviewer {
	return &Reviewer{provider: p, model: model, workDir: workDir}
}

// Review executes the AI reviewer for the given task and parses the verdict.
func (r *Reviewer) Review(ctx context.Context, t *types.Task) (*ReviewResult, error) {
	prompt := buildReviewerPrompt(t)

	result, err := r.runStep(ctx, r.provider, types.ExecuteRequest{
		Prompt:       prompt,
		Model:        r.model,
		WorkDir:      r.workDir,
		AllowedTools: []string{"Read", "Glob", "Grep", "Bash"},
	})
	if err != nil {
		return nil, fmt.Errorf("reviewer execution for task %s: %w", t.ID, err)
	}

	rr := parseVerdict(result.Output)
	rr.CostUSD = result.CostUSD
	rr.TokensIn = result.TokensIn
	rr.TokensOut = result.TokensOut
	rr.DurationMs = result.DurationMs
	return rr, nil
}

func buildReviewerPrompt(t *types.Task) string {
	var b strings.Builder

	fmt.Fprintf(&b, `You are a code reviewer for Corvex. Verify that this task was completed correctly.

## Task: %s — %s

### Description

%s

### Success Criteria

`, t.ID, t.Title, t.Description)

	for _, c := range t.Criteria {
		fmt.Fprintf(&b, "- %s\n", c)
	}

	b.WriteString("\n### Expected Files\n\n")
	for _, f := range t.Files.Create {
		fmt.Fprintf(&b, "- Should exist (created): %s\n", f)
	}
	for _, f := range t.Files.Modify {
		fmt.Fprintf(&b, "- Should be modified: %s\n", f)
	}

	b.WriteString(`
## Source of Truth

The task description above was generated by the Planner from the project's
spec.md. The Planner sometimes compacts decisions in lossy ways (especially
numbers, timing, ordering, and units). **spec.md is the source of truth, not
the task description.**

Before judging, you MUST:
1. Locate the project's spec via Glob: ` + "`.corvex/tasks/*/spec.md`" + `
2. Read the section(s) relevant to this task
3. If decisions.md exists alongside spec.md, read it too — it carries
   resolved design decisions from the grilling phase

If the task description and spec.md disagree, **spec.md wins**. Judge the
implementation against spec.md.

## Verification Steps

1. Check that all files listed as "created" exist on disk
2. Read spec.md (and decisions.md if present) for sections relevant to this task
3. Verify each success criterion by reading the relevant code, using spec.md
   as the authoritative requirement
4. If criteria include commands (like tests, builds), run them
5. Check git diff for the task's changes

## Output Format

End your response with EXACTLY one of these lines:
VERDICT: PASS
VERDICT: FAIL

When the verdict is FAIL, also include a CATEGORY: line right before the
verdict, choosing exactly one of:
- wrong-approach     — the implementation took the wrong design or direction
- missing-edge-case  — works for the happy path but misses important edge cases
- incomplete         — one or more success criteria are not fully addressed
- flaky-test         — failing tests appear flaky or environment-dependent
- style              — only style / convention issues
- ambiguity          — the task description contradicts or under-specifies
                       spec.md; the implementation matches one plausible
                       reading but the requirement itself is unclear. Cite
                       both the task line and the spec line in your analysis.

Use ` + "`ambiguity`" + ` instead of ` + "`wrong-approach`" + ` when the implementation is
defensible against spec.md but the task description points the other way —
this is a Planner compaction bug, not a Worker bug. The orchestrator routes
` + "`ambiguity`" + ` failures to human review rather than blind retries.

Example:
CATEGORY: missing-edge-case
VERDICT: FAIL

Before those lines, provide your analysis. When citing spec.md or
tasks.md, quote the exact line so a human can audit the call.
`)

	return b.String()
}

func parseVerdict(output string) *ReviewResult {
	lines := strings.Split(output, "\n")

	verdict := VerdictFail
	verdictIdx := -1

	for i := len(lines) - 1; i >= 0; i-- {
		upper := strings.TrimSpace(strings.ToUpper(lines[i]))
		if upper == "VERDICT: PASS" {
			verdict = VerdictPass
			verdictIdx = i
			break
		}
		if upper == "VERDICT: FAIL" {
			verdict = VerdictFail
			verdictIdx = i
			break
		}
	}

	// Category is only meaningful on FAIL. Search the last few lines for a
	// CATEGORY: marker; tolerate whitespace and casing.
	category := ""
	if verdict == VerdictFail {
		start := verdictIdx - 5
		if start < 0 {
			start = 0
		}
		end := verdictIdx
		if end < 0 {
			end = len(lines)
		}
		for i := end - 1; i >= start; i-- {
			line := strings.TrimSpace(lines[i])
			upper := strings.ToUpper(line)
			if strings.HasPrefix(upper, "CATEGORY:") {
				category = strings.TrimSpace(line[len("CATEGORY:"):])
				category = strings.ToLower(category)
				break
			}
		}
	}

	summary := strings.TrimSpace(output)
	if verdictIdx > 0 {
		summary = strings.TrimSpace(strings.Join(lines[:verdictIdx], "\n"))
	}

	return &ReviewResult{
		Verdict:  verdict,
		Category: category,
		Summary:  summary,
	}
}
