package step

import (
	"fmt"
	"strings"

	"github.com/giovannialves/corvex/internal/types"
)

func buildReviewerPrompt(t *types.Task, skill string) string {
	var b strings.Builder

	fmt.Fprintf(&b, `You are a code reviewer for Corvex. Verify that this task was completed correctly.

## Task: %s — %s

### Description

%s

### Success Criteria

`, t.ID, t.Title, t.Description)

	if skill != "" {
		fmt.Fprintf(&b, "Use the `%s` skill (via the Skill tool) to guide your review.\n\n", skill)
	}

	for _, c := range t.Criteria {
		fmt.Fprintf(&b, "- %s\n", c)
	}

	b.WriteString("\n### Expected Files\n\n")
	for _, f := range t.Files.Create {
		fmt.Fprintf(&b, "- Should exist (created): %s\n", f)
	}
	for _, f := range t.Files.Modify {
		fmt.Fprintf(&b, "- Should be modified: %s\n", f)
	}

	b.WriteString(`
## Source of Truth

The task description above was generated by the Planner from the project's
spec.md. The Planner sometimes compacts decisions in lossy ways (especially
numbers, timing, ordering, and units). **spec.md is the source of truth, not
the task description.**

Before judging, you MUST:
1. Locate the project's spec via Glob: ` + "`.corvex/tasks/*/spec.md`" + `
2. Read the section(s) relevant to this task
3. If decisions.md exists alongside spec.md, read it too — it carries
   resolved design decisions from the grilling phase

If the task description and spec.md disagree, **spec.md wins**. Judge the
implementation against spec.md.

## Verification Steps

1. Check that all files listed as "created" exist on disk
2. Read spec.md (and decisions.md if present) for sections relevant to this task
3. Verify each success criterion by reading the relevant code, using spec.md
   as the authoritative requirement
4. If criteria include commands (like tests, builds), run them
5. Check git diff for the task's changes

## Output Format

End your response with EXACTLY one of these lines:
VERDICT: PASS
VERDICT: FAIL

When the verdict is FAIL, also include a CATEGORY: line right before the
verdict, choosing exactly one of:
- wrong-approach     — the implementation took the wrong design or direction
- missing-edge-case  — works for the happy path but misses important edge cases
- incomplete         — one or more success criteria are not fully addressed
- flaky-test         — failing tests appear flaky or environment-dependent
- style              — only style / convention issues
- ambiguity          — the task description contradicts or under-specifies
                       spec.md; the implementation matches one plausible
                       reading but the requirement itself is unclear. Cite
                       both the task line and the spec line in your analysis.

Use ` + "`ambiguity`" + ` instead of ` + "`wrong-approach`" + ` when the implementation is
defensible against spec.md but the task description points the other way —
this is a Planner compaction bug, not a Worker bug. The orchestrator routes
` + "`ambiguity`" + ` failures to human review rather than blind retries.

Example:
CATEGORY: missing-edge-case
VERDICT: FAIL

Before those lines, provide your analysis. When citing spec.md or
tasks.md, quote the exact line so a human can audit the call.
`)

	return b.String()
}
