// Package run gives a run an identity that outlives the process that started
// it.
//
// Before this package, everything was scoped by *project* (a directory under
// `.corvex/tasks/`), the repository was implicit (the cwd) and two executions
// of the same project were indistinguishable in the ledger. Here a run gets:
//
//   - an id (`run_8f21`) generated by an injectable generator;
//   - a record on disk in the repository (`.corvex/runs/<run_id>.json`) holding
//     run_id, repo, recipe/project, pid, started_at, status and updated_at,
//     written atomically (temp file + rename) so a run killed mid-write cannot
//     leave half a JSON object behind;
//   - a heartbeat that refreshes updated_at, so a run killed with SIGKILL
//     (which never gets to write a terminal status) can still be told apart
//     from one that is genuinely working;
//   - a line in the global index (`$CORVEX_HOME/runs.jsonl`, default
//     `~/.corvex/runs.jsonl`) at start and at every status change, so a second
//     process — the F7 server, or another CLI invocation — can list runs across
//     repositories without knowing where they live.
//
// # Layering
//
// This package writes and reads state; it does not discover it. The absolute
// path of the git root arrives as an input (`Registry.Repo`) instead of being
// resolved here, so `internal/run` stays free of `internal/ops` (which will
// depend on it, not the other way round). There is no cobra, no stdout and no
// os.Exit: the same functions serve the CLI today and HTTP handlers later.
//
// # What is never recorded
//
// No environment, token, credential or resolved env allowlist. The fields are
// fixed by the Record struct, so there is no shape for a secret to travel in —
// and the global index lives in the user's home, which is more exposed than a
// per-repository ledger, so it is written 0600 inside a 0700 directory.
package run
